### ISSUE TITLE
Snail Speed Request

### ISSUE THREAD

**Issue by Snailman-Axl** [IdylRS/snailman#2]
Hi IdlyIRS,

Thank you for creating this plugin. Really having a lot of fun!

Is there a way to deactivate the snail speed-up when it gets close by? I'd rather have it move at a consistent speed whether it is close or far. Thanks!

- RSN Snailman Axl

**Comment by IdylRS** [comment]
This will be in the next version! Thanks for the feedback :)

**Comment by Snailman-Axl** [comment]
Sweet! Thank you!!
